Repository dbinclui-org/dbinclui-frontend, pull requests merged in 2021-12, with the labels that each got.

#1 Adicionando Readme padrão no frontend
  README.md
Labels: documentation

#3 Feature/dbi 49 - Configurar biblioteca e estrutura de roteamento/navegação
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/acessibility-guide/index.tsx
  src/pages/deaf-culture-guide/index.tsx
  src/pages/error/404.tsx
  src/pages/home/index.tsx
Labels: feature

#4 Feature/dbi 60 - Prettier e ESLINT
  .eslintrc.json
  .prettierrc
  README.md
  package-lock.json
  src/index.tsx
Labels: feature

#15 adiciona o widget VLibras nas páginas
  src/App.tsx
  src/index.tsx
Labels: feature

#14 Feature/dbi-61 - Atualizar o READ ME com o fluxo do git flow
  README.md
Labels: documentation

#17 Feature/dbi-70 - Atualizar grade de tecnologias no documento do projeto
  README.md
Labels: documentation

#16 insere estrutura de rotas no app.tsx e importa somente app no index
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  yarn.lock
Labels: feature

#18 Feature/dbi 68 - Adicionar no README do frontend o boilerplate de como devem ser construído os componentes
  .vscode/settings.json
  README.md
Labels: documentation

#24 Feature/dbi 53
  .eslintrc.json
  .prettierrc
  mockserver/db.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/svgs/404.tsx
  src/pages/acessibility-guide/AcessibilityGuide.test.tsx
  src/pages/acessibility-guide/index.tsx
  src/pages/acessibility-guide/styles.css
  src/pages/error/404.test.tsx
  src/pages/error/404.tsx
  src/pages/error/styles.css
  src/services/.gitkeep
  src/services/api.ts
  src/services/guides.ts
  src/tests/services/guides.test.ts
  yarn.lock
Labels: feature

#25 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#22 Criar rota para página
  src/App.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/styles.css
Labels: feature

#21 Feature/dbi us001-10 - US001 - [Front] - Fazer footer
  package-lock.json
  package.json
  src/components/Footer/Footer.test.tsx
  src/components/Footer/index.tsx
  src/components/Footer/styles.css
  src/index.tsx
  src/pages/acessibility-guide/styles.css
  src/pages/home/index.tsx
  src/pages/home/styles.css
  yarn.lock
Labels: feature

#28 Feature/DBI-US002-16 - Criar rota para página
  package-lock.json
  src/App.tsx
  src/index.tsx
  src/pages/admin/index.tsx
  src/pages/home/index.tsx
  src/pages/layout/index.tsx
  src/routes/routes.tsx
  yarn.lock
Labels: enhancement, feature

#29 Feature/DBI-US001-7 - Criar Theme Global
  package-lock.json
  package.json
  src/components/Card/styles.css
  src/components/Menu-acessibility/index.tsx
  src/components/Menu-acessibility/styles.css
  src/index.tsx
  src/pages/acessibility-guide/index.tsx
  src/pages/acessibility-guide/styles.css
  src/pages/home/style.css
  src/styles/colors.ts
  src/styles/theme.ts
  yarn.lock
Labels: feature

#27 Feature/dbi us001-10 - Fazer footer
  package-lock.json
  package.json
  public/index.html
  src/components/Footer/Footer.test.tsx
  src/components/Footer/index.tsx
  src/components/Footer/styles.css
  src/pages/error/styles.css
  src/pages/home/index.tsx
  src/pages/home/style.css
  src/pages/home/styles.css
  src/pages/layout/index.tsx
  src/pages/layout/styles.css
  yarn.lock
Labels: feature

#32 Develop
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Card/styles.css
  src/components/Footer/Footer.test.tsx
  src/components/Footer/index.tsx
  src/components/Footer/styles.css
  src/components/Menu-acessibility/index.tsx
  src/components/Menu-acessibility/styles.css
  src/index.tsx
  src/pages/acessibility-guide/index.tsx
  src/pages/acessibility-guide/styles.css
  src/pages/admin/index.tsx
  src/pages/error/styles.css
  src/pages/home/index.tsx
  src/pages/home/style.css
  src/pages/layout/index.tsx
  src/pages/layout/styles.css
  src/pages/register-guide/index.tsx
  src/pages/register-guide/styles.css
  src/routes/routes.tsx
  src/styles/colors.ts
  src/styles/theme.ts
  yarn.lock
Labels: release
