Repository dbinclui-org/dbinclui-frontend, pull requests merged in 2022-01, with the labels that each got.

#30 feature/DBI-US003-22 - US003 - [Front] - Validar dados
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Counter/index.tsx
  src/components/Footer/styles.css
  src/components/MenuAcessibility/index.tsx
  src/index.tsx
  src/pages/acessibility-guide/styles.css
  src/pages/home/index.tsx
  src/pages/home/style.css
  src/pages/layout/style.css
  src/pages/register-guide/RegisterGuide.test.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/validator.test.tsx
  src/pages/register-guide/validator.ts
  src/styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: feature

#35 Feature/dbi us002 13 - US002 - [Front] - Fazer o layout de acordo com o protótipo
  src/pages/admin/Admin.test.tsx
  src/pages/admin/index.tsx
Labels: feature

#34 Feature/dbi 31 - Definir Paths no tsconfig.json
  .eslintrc.json
  config-overrides.js
  jest.config.ts
  package-lock.json
  package.json
  src/pages/acessibility-guide/AcessibilityGuide.test.tsx
  src/routes/routes.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#36 Feature/dbi-US001-9 - US001 - [Front] - Fazer header
  .eslintrc.json
  .prettierrc
  package-lock.json
  public/index.html
  src/App.tsx
  src/assets/logo.png
  src/assets/logo.svg
  src/components/.gitkeep
  src/components/Header/header.test.tsx
  src/components/Header/index.tsx
  src/components/Header/styles.css
  src/components/svgs/logo.tsx
  src/pages/error/404.tsx
  src/pages/layout/index.tsx
  yarn.lock
Labels: feature

#40 Feature/dbi us001-8 - Fazer o layout de acordo com o protótipo
  package-lock.json
  public/index.html
  src/components/CardHome/cardhome.test.tsx
  src/components/CardHome/index.tsx
  src/components/Footer/styles.css
  src/components/Header/index.tsx
  src/pages/home/home.test.tsx
  src/pages/home/index.tsx
  src/pages/home/style.css
  src/pages/layout/styles.css
  yarn.lock
Labels: feature

#39 Bugfix/DBI-US002-36 - US002 - [Front] - Bug | Configurar rota do header para admin
  src/components/Header/header.test.tsx
  src/components/Header/index.tsx
Labels: bug

#38 Feature/dbi us003 21 - US003 - [Front] - Fazer o layout de acordo com o protótipo
  src/pages/register-guide/RegisterGuide.test.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/styles.css
  src/pages/register-guide/styles.ts
  src/services/guides.ts
Labels: feature

#41 [conifg]: Variavel de ambiente para url base
  src/services/api.ts
Labels: feature

#51 feature/DBI-US007-34 - US007 - [Front] - Criar rota para página
  src/pages/register-category/index.tsx
  src/routes/routes.tsx
Labels: feature

#52 Feature/US003/US007/US011-DBI-56 - Criação de um componente de mensagens de confirmação ou erro
  src/components/Notification/index.tsx
  src/components/Notification/notification.test.tsx
Labels: feature

#53 bugfix/ISSUE-46 - ISSUE-46 - [Frontend] - Ajustes no código
  src/pages/home/home.test.tsx
  src/pages/register-guide/RegisterGuide.test.tsx
  src/pages/register-guide/styles.ts
Labels: enhancement

#57 Bugfix/DBI-ISSUE-42 - ISSUE-42 - [Config] - Ajustes build.yaml
  .github/workflows/build.yaml
Labels: enhancement

#56 bugfix/Notification-onClose-78 - Adicionar propriedade `onClose` ao componente de notificação
  src/components/Notification/index.tsx
  src/components/Notification/notification.test.tsx
Labels: bug

#54 Feature/dbi us007-33 - Fazer o layout de acordo com o protótipo
  src/components/Header/styles.css
  src/pages/register-category/RegisterCategory.test.tsx
  src/pages/register-category/index.tsx
  src/pages/register-category/styles.ts
  src/routes/routes.tsx
Labels: feature

#58 Feature/DBI-US001-19-S2 - [Débito técnico] Cores com o Vlibras
  src/assets/logo.svg
  src/components/AcessibilityTools/index.tsx
  src/components/AcessibilityTools/style.css
  src/components/AcessibilityTools/styles.ts
  src/components/CardHome/index.tsx
  src/components/Counter/index.tsx
  src/components/Footer/index.tsx
  src/components/Header/styles.css
  src/components/svgs/404.tsx
  src/components/svgs/logo.tsx
  src/components/svgs/logoBranca.tsx
  src/pages/home/index.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/styles.ts
  src/styles/colors.ts
  src/styles/theme.ts
Labels: feature

#59 feature/DBI-US011-46 - US011 - [Front] - Criar rota para página
  src/pages/admin/Admin.test.tsx
  src/pages/admin/index.tsx
  src/pages/register-digital-content/index.tsx
  src/routes/routes.tsx
Labels: feature

#61 Feature/DBI-US007-30 - Front - Validar dados
  src/pages/register-category/validator.test.ts
  src/pages/register-category/validator.ts
Labels: feature

#55 Feature/DBI-US003-58 - US003 - Front - Implementar a funcionalidade botão Salvar
  .eslintrc.json
  package.json
  src/App.tsx
  src/components/AcessibilityTools/index.tsx
  src/pages/acessibility-guide/AcessibilityGuide.test.tsx
  src/pages/acessibility-guide/index.tsx
  src/pages/error/404.tsx
  src/pages/layout/index.tsx
  src/pages/register-guide/RegisterGuide.test.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/validator.test.tsx
  src/pages/register-guide/validator.ts
  src/services/api.ts
  src/services/guides.ts
  src/services/guides/guides.test.ts
  src/services/guides/index.ts
  src/tests/.gitkeep
  src/tests/services/guides.test.ts
Labels: feature

#62 Feature/DBI-US011-44 - US011 - [Front] - Fazer o layout de acordo com o protótipo
  src/pages/register-category/index.tsx
  src/pages/register-digital-content/RegisterDigitalContent.test.tsx
  src/pages/register-digital-content/index.tsx
  src/pages/register-digital-content/styles.ts
Labels: feature

#67 bugfix/DBI-ISSUE-80 - [Frontend] - Remover dependências não utilizadas
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: documentation, enhancement

#68 bugfix/DBI-ISSUE-81 - [Frontend] - Passar valor inicial para o componente Select
  src/pages/register-category/index.tsx
  src/pages/register-digital-content/index.tsx
Labels: bug

#71 bugfix/DBI-ISSUE-84 - [Frontend] - Adicionar arquivo _redirects do netlify
  public/_redirects
Labels: enhancement

#72 Feature/DBI-US-007-59 - (4) US007 - [Front] - Implementar a funcionalidade botão Salvar
  src/pages/register-category/RegisterCategory.test.tsx
  src/pages/register-category/index.tsx
  src/pages/register-guide/RegisterGuide.test.tsx
  src/services/categories/index.ts
  src/services/guides/index.ts
Labels: feature

#74 bugfix/DBI-ISSUE-73 - Ajustar botões da página do admin
  src/pages/admin/index.tsx
Labels: enhancement

#76 bugfix/DBI-ISSUE-77 - Adicionar Roboto ao typography no theme
  public/index.html
  src/styles/theme.ts
Labels: bug

#78 Bugfix/DBI-ISSUE-74-ISSUE-74 - [Frontend] - Nav Bar interferindo no Scroll da página
  src/components/Header/index.tsx
Labels: bug

#77 bugfix/DBI-ISSUE-72 - [Frontend] - Mudar posição do menu de acessibilidade (acima do Widget do VLibras)
  src/components/AcessibilityTools/styles.ts
Labels: bug

#80 feature/DBI-ISSUE-75 - [Frontend] - Mudar os botões de FECHAR para VOLTAR e utilizar href
  src/pages/register-category/RegisterCategory.test.tsx
  src/pages/register-category/index.tsx
  src/pages/register-digital-content/RegisterDigitalContent.test.tsx
  src/pages/register-digital-content/index.tsx
  src/pages/register-digital-content/styles.ts
  src/pages/register-guide/RegisterGuide.test.tsx
  src/pages/register-guide/index.tsx
Labels: feature

#81 feature/DBI-US011-47 - [Front] - Ajuste no Theme Global
  src/pages/error/styles.css
  src/pages/layout/styles.css
Labels: enhancement

#82 Feature/DBI-US011-60 - [Front] - Implementar a funcionalidade botão Salvar
  public/index.html
  src/pages/register-category/RegisterCategory.test.tsx
  src/pages/register-category/index.tsx
  src/pages/register-category/styles.ts
  src/pages/register-digital-content/RegisterDigitalContent.test.tsx
  src/pages/register-digital-content/index.tsx
  src/pages/register-digital-content/styles.ts
  src/pages/register-digital-content/validator.test.tsx
  src/pages/register-digital-content/validator.ts
  src/pages/register-guide/RegisterGuide.test.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/styles.ts
  src/services/api.ts
  src/services/categories/index.ts
  src/services/digitalContent/index.ts
  src/services/guides/index.ts
Labels: feature

#85 Develop
  .github/workflows/build.yaml
Labels: enhancement

#86 feature/DBI-US016-24 - FRONT - Consumir os guias do banco de dados
  src/components/CardHome/cardhome.test.tsx
  src/components/CardHome/index.tsx
  src/pages/acessibility-guide/AcessibilityGuide.test.tsx
  src/pages/acessibility-guide/index.tsx
  src/pages/acessibility-guide/styles.css
  src/pages/deaf-culture-guide/index.tsx
  src/pages/guides/index.tsx
  src/pages/home/home.test.tsx
  src/pages/home/index.tsx
  src/routes/routes.tsx
Labels: feature

#88 feature/DBI-US005-17 - FRONT - Formulário de edição de guia
  src/pages/update-guide/UpdateGuide.test.tsx
  src/pages/update-guide/index.tsx
  src/pages/update-guide/styles.ts
  src/pages/update-guide/validator.test.tsx
  src/pages/update-guide/validator.ts
  src/routes/routes.tsx
Labels: feature

#87 Feature/DBI-US009-31 - FRONT - Formulário de edição de categoria de guia
  src/pages/update-category/UpdateCategory.test.tsx
  src/pages/update-category/index.tsx
  src/pages/update-category/styles.ts
  src/pages/update-category/validator.test.ts
  src/pages/update-category/validator.ts
  src/routes/routes.tsx
Labels: feature

#89 Feature/DBI-US031-26 - [US031] FRONT - Buscar os dados do Backend
  src/components/CardHome/cardhome.test.tsx
  src/components/CardHome/index.tsx
  src/pages/guide-page/category-section/index.tsx
  src/pages/guide-page/category-section/styles.ts
  src/pages/guide-page/index.tsx
  src/pages/home/index.tsx
  src/pages/register-digital-content/RegisterDigitalContent.test.tsx
  src/pages/register-digital-content/index.tsx
  src/pages/register-guide/index.tsx
  src/routes/routes.tsx
  src/services/categories/index.ts
  src/services/digitalContent/index.ts
  src/services/guides/guides.test.ts
  src/services/guides/index.ts
Labels: feature

#92 Feature/DBI-US004-15 - FRONT - Fazer o layout de acordo com o protótipo
  package-lock.json
  package.json
  src/pages/admin/index.tsx
  src/pages/guide-list/GuideList.test.tsx
  src/pages/guide-list/index.tsx
  src/pages/guide-list/styles.ts
  src/routes/routes.tsx
  yarn.lock
Labels: feature

#93 Feature/DBI-US012-40 - FRONT - Fazer o layout de acordo com o protótipo
  src/pages/list-digital-content/ListDigitalContent.test.tsx
  src/pages/list-digital-content/index.tsx
  src/pages/list-digital-content/styles.ts
  src/pages/register-digital-content/index.tsx
  src/routes/routes.tsx
Labels: feature

#91 Feature/DBI-US008-29 - FRONT - Fazer o layout de acordo com o protótipo
  package-lock.json
  src/pages/admin/Admin.test.tsx
  src/pages/admin/index.tsx
  src/pages/categories-list/CategoriesList.test.tsx
  src/pages/categories-list/index.tsx
  src/pages/categories-list/styles.ts
  src/pages/register-category/RegisterCategory.test.tsx
  src/pages/register-category/index.tsx
  src/pages/update-category/UpdateCategory.test.tsx
  src/pages/update-category/index.tsx
  src/routes/routes.tsx
  yarn.lock
Labels: feature

#95 bugfix/DBI-ISSUE-75 - [Frontend/Backend] - Nomenclatura das rotas no padrão REST
  src/services/categories/index.ts
  src/services/digitalContent/index.ts
  src/services/guides/guides.test.ts
  src/services/guides/index.ts
Labels: enhancement
