Repository dbinclui-org/dbinclui-frontend, pull requests merged in 2022-02, with the labels that each got.

#94 Feature/DBI-US031-57 - [US031] FRONT - Fazer o layout de acordo com o protótipo
  package-lock.json
  package.json
  src/components/AccessibilityTypography/index.tsx
  src/components/ImageCarroussel/ImageCarroussel.test.tsx
  src/components/ImageCarroussel/index.tsx
  src/components/ImageCarroussel/styles.ts
  src/pages/guide-page/category-section/categorySection.test.tsx
  src/pages/guide-page/category-section/index.tsx
  src/pages/guide-page/category-section/styles.ts
  src/pages/guide-page/guide-page.test.tsx
  src/pages/guide-page/index.tsx
  src/pages/guide-page/styles.ts
  src/pages/guides/index.tsx
  src/pages/register-digital-content/index.tsx
  src/routes/routes.tsx
  src/styles/theme.ts
  yarn.lock
Labels: feature

#97 Bugfix/DBI-ISSUE-90 - Retornos web service
  package-lock.json
  src/pages/guide-page/index.tsx
  src/pages/home/home.test.tsx
  src/pages/home/index.tsx
  src/pages/register-category/RegisterCategory.test.tsx
  src/pages/register-category/index.tsx
  src/pages/register-digital-content/RegisterDigitalContent.test.tsx
  src/pages/register-digital-content/index.tsx
  src/pages/update-category/UpdateCategory.test.tsx
  src/pages/update-category/index.tsx
  src/services/api.ts
  src/services/categories/index.ts
  src/services/digitalContent/index.ts
  src/services/guides/index.ts
Labels: bug, enhancement

#98 Feature/DBI-US004-16 - [US004] FRONT - Buscar os dados do Backend
  src/pages/guide-list/GuideList.test.tsx
  src/pages/guide-list/index.tsx
  src/routes/routes.tsx
Labels: feature

#100 Feature/DBI-US005-20 - FRONT - Submeter formulário
  src/pages/register-guide/index.tsx
  src/pages/update-category/index.tsx
  src/pages/update-guide/UpdateGuide.test.tsx
  src/pages/update-guide/index.tsx
  src/routes/routes.tsx
  src/services/guides/guides.test.ts
  src/services/guides/index.ts
Labels: feature

#101 Feature/DBI-US008-30 - FRONT - Buscar os dados do Backend
  src/pages/categories-list/CategoriesList.test.tsx
  src/pages/categories-list/index.tsx
  src/pages/categories-list/styles.ts
  src/routes/routes.tsx
Labels: feature

#99 Feature/DBI-US012-38 - FRONT - Buscar os dados do Backend
  package-lock.json
  package.json
  src/components/AcessibilityTools/AccessibilityTools.test.tsx
  src/components/CardHome/cardhome.test.tsx
  src/components/CardHome/index.tsx
  src/components/Footer/index.tsx
  src/components/Header/header.test.tsx
  src/pages/admin/Admin.test.tsx
  src/pages/admin/index.tsx
  src/pages/guide-page/category-section/categorySection.test.tsx
  src/pages/guide-page/category-section/index.tsx
  src/pages/list-digital-content/ListDigitalContent.test.tsx
  src/pages/list-digital-content/index.tsx
  src/routes/routes.tsx
  src/services/digitalContent/digitalContent.test.ts
  src/services/digitalContent/index.ts
Labels: feature

#105 Feature/DBI-US013-44 - [US013 - LAYOUT] FRONT - Formulário de edição do conteúdo digital
  src/pages/update-digital-content/UpdateDigitalContent.test.tsx
  src/pages/update-digital-content/index.tsx
  src/pages/update-digital-content/styles.ts
  src/pages/update-digital-content/validator.test.tsx
  src/pages/update-digital-content/validator.ts
  src/routes/routes.tsx
Labels: feature

#107 BUGFIX/DBI-ISSUE-106 - Adequar consumo de conteúdo digital após mudanças no backend
  src/components/ImageCarroussel/ImageCarroussel.test.tsx
  src/components/ImageCarroussel/index.tsx
  src/pages/guide-page/category-section/categorySection.test.tsx
  src/pages/guide-page/guide-page.test.tsx
  src/pages/list-digital-content/index.tsx
  src/pages/update-guide/index.tsx
  src/services/digitalContent/index.ts
Labels: bug

#108 Feature/DBI-US006-US010-US014-73 - Criar componente de exclusão
  src/components/DialogBox/DialogBoxConfirmation/DialogBoxConfirmation.test.tsx
  src/components/DialogBox/DialogBoxConfirmation/index.tsx
  src/components/DialogBox/DialogBoxConfirmation/styles.ts
  src/pages/guide-list/GuideList.test.tsx
  src/pages/guide-list/index.tsx
  src/services/guides/index.ts
Labels: feature

#109 feature/DBI-M01-51 - Fazer o Layout de acordo com o protótipo - HOME
  src/components/Header/index.tsx
  src/pages/home/index.tsx
Labels: feature

#110 Feature/DBI-US009-35- FRONT - Submeter formulário
  src/pages/categories-list/index.tsx
  src/pages/update-category/UpdateCategory.test.tsx
  src/pages/update-category/index.tsx
  src/services/categories/index.ts
Labels: feature

#111 Feature/DBI-US013-46 - FRONT - Submeter formulário
  src/pages/update-digital-content/UpdateDigitalContent.test.tsx
  src/pages/update-digital-content/index.tsx
  src/pages/update-digital-content/validator.ts
  src/services/digitalContent/digitalContent.test.ts
  src/services/digitalContent/index.ts
  src/services/guides/index.ts
Labels: feature

#112 Feature/DBI-US010-37 - Executar ação de exclusão botão "excluir"
  src/pages/categories-list/CategoriesList.test.tsx
  src/pages/categories-list/index.tsx
  src/services/categories/categories.test.ts
  src/services/categories/index.ts
Labels: feature

#113 Feature/DBI-US006-22 - Executar ação de exclusão botão "excluir"
  src/components/ImageCarroussel/ImageCarroussel.test.tsx
  src/components/ImageCarroussel/index.tsx
  src/pages/guide-list/GuideList.test.tsx
  src/pages/guide-list/index.tsx
  src/pages/guide-page/guide-page.test.tsx
  src/pages/update-digital-content/index.tsx
  src/services/guides/index.ts
Labels: feature

#118 Bugfix/DBI-ISSUE-80 - Refatoração de testes (e alguns ajustes)
  public/favicon.ico
  src/components/ImageCarroussel/index.tsx
  src/components/ImageCarroussel/styles.ts
  src/pages/categories-list/index.tsx
  src/pages/guide-list/index.tsx
  src/pages/guide-page/category-section/styles.ts
  src/pages/guide-page/index.tsx
  src/pages/guide-page/styles.ts
  src/pages/list-digital-content/index.tsx
  src/pages/register-category/index.tsx
  src/pages/register-category/styles.ts
  src/pages/register-digital-content/RegisterDigitalContent.test.tsx
  src/pages/register-digital-content/index.tsx
  src/pages/register-guide/index.tsx
  src/pages/register-guide/styles.ts
  src/pages/update-category/UpdateCategory.test.tsx
  src/pages/update-category/index.tsx
  src/pages/update-category/styles.ts
  src/pages/update-category/validator.test.ts
  src/pages/update-digital-content/UpdateDigitalContent.test.tsx
  src/pages/update-guide/UpdateGuide.test.tsx
  src/pages/update-guide/index.tsx
  src/pages/update-guide/styles.ts
  src/services/api.test.ts
  src/services/categories/categories.test.ts
  src/services/digitalContent/digitalContent.test.ts
  src/services/guides/guides.test.ts
  src/styles/theme.ts
Labels: bug, feature

#119 Feature/DBI-M02-52 - Ajustes do Sobre
  src/pages/about/about.test.tsx
Labels: feature
